add-affinity-nodeselector-tolerations-to-chao (#57)
* Introduce affinity, nodeSelector, and tolerations to the Chao deployment chart.  See https://gremlininc.slack.com/archives/C010HA9NQK1/p1633649317296600 for more details.

* https://github.com/gremlin/helm/pull/57/files#r749668311

* Add a summary for chao.nodeSelector, chao.tolerations, chao.affinity.  Add the same three to values.yaml.

* use nindent to fix yaml

Without this change, we get the following error when specifying an affinity:

```
Error: YAML parse error on gremlin/templates/chao-deployment.yaml: error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context
```

debug output yields the answer:

```
...
      affinity:         nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube
...
```

* use nindent to fix yaml

Without this change, we get the following error when specifying an affinity:

```
Error: YAML parse error on gremlin/templates/daemonset.yaml: error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
```

debug output yields the answer:

```
...
      affinity:         nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - minikube
...
```

Co-authored-by: Phil Gebhardt <phil@gremlin.com>